---
reference: hg38
genotyper: wssd_cc
data_types:
    - wssd
    - sunk
bedfiles: 
    TCAF: dat/regions.bed
datasets: 
    - hgdp
    - archaics
    - nhp
main_dataset: 
    - hgdp
append_dataset: 
    - archaics
    - nhp
master_manifest: /net/eichler/vol26/eee_shared/whole_genome_resources/all_diversity.manifest.filtered.tab
pop_codes: dat/super_pop_codes.tab
table_dir: tables
plot_dir: plots
plot_file_type: 
    - png
    - pdf
gene_gram_settings: --color_column super_pop --hclust --include_coords --label_heatmap --xmin 0.05 --yspace 0.075 --xspace 0.08
spp: 500
datasets_file: dat/datasets.tab
ref_files:
    hg19:
        contigs: /net/eichler/vol26/eee_shared/assemblies/hg19/legacy/hg19_contigs.txt
        wssd_mask: /net/eichler/vol26/eee_shared/assemblies/hg19/legacy/mask_tracks/HG19-noWM-pad36
        sunk_mask: /net/eichler/vol26/eee_shared/assemblies/hg19/legacy/sunk_tracks/hg19_sunk_depth_mask.dts
        sunk_bed: /net/eichler/vol26/eee_shared/assemblies/hg19/legacy/sunks/hg19_suns.no_repeats_36bp_flanking.bed
    hg38: 
        contigs: /net/eichler/vol26/eee_shared/nobackups/archive/assemblies/hg38/read_depth/illumina/hg38_contigs.tab
        wssd_mask: /net/eichler/vol26/eee_shared/nobackups/archive/assemblies/hg38/read_depth/illumina/hg38_noWM_pad36
        sunk_mask: /net/eichler/vol26/eee_shared/nobackups/archive/assemblies/hg38/read_depth/illumina/hg38_sunk_mask_track_pad36_e0.dts
        sunk_bed: /net/eichler/vol26/eee_shared/nobackups/archive/assemblies/hg38/sunks/suns.no_repeats_36bp_flanking.bed
